### ISSUE TITLE
Super simple and simple mode

### ISSUE THREAD

**Issue by Albert221** [Albert221/FastShopping#15]
When the user firstly opens the app, show him two app modes to choose from.

- **One list.** The functionality from the v1 version of the app. It utilizes the same state management, but uses only one shopping list.

- **Multiple lists.** The current interface.

![image](https://user-images.githubusercontent.com/4085280/85933108-89ef6800-b8d3-11ea-9bc5-c9cd4c211712.png)

**Comment by Albert221** [comment]
<img src="https://user-images.githubusercontent.com/4085280/85933640-a8586200-b8d9-11ea-862e-545b82b1ebb6.png" width="300">

**Comment by natrius** [comment]
Thats a good mode actually. Some people just want one list for shopping and nothing else.
