### ISSUE TITLE
Adding categories for items

### ISSUE THREAD

**Issue by e-edgren** [Albert221/FastShopping#19]
It would be neat to be able to create categories in the item list and to add items to these categories.

Categories must be in free text and to sort items according to where they are in the store.

Example (I don't know that the sections are called in English since I live in Sweden, but I think you get the idea):

Pasta
- Spaghetti
- Macaroni

Milk
- Condensed milk
- Milk
- Butter

**Comment by natrius** [comment]
Or even "travelling", for example.

**Comment by Albert221** [comment]
Thank you for your idea! But Fast Shopping is all about simplicity. Categories are something that would make the application more complex and less obvious to use for people that are not as tech-savvy as probably you and me. Therefore I'm closing it as wontfix.

However, if you have an idea on how to add that feature without introducing any new steps or visual clutter, I'm interested to hear that. Although I can't come up with anything like that myself.
