### ISSUE TITLE
Option for dropping checked items to the bottom

### ISSUE THREAD

**Issue by natrius** [Albert221/FastShopping#20]
Otherwise for a long list you have to scroll down to check something and search. This way everything missing is on top and in sight.

**Comment by Albert221** [comment]
This can be done when the user marked an item as done and collapsed the item. Then, this very item would go to the bottom of the list.

**Comment by natrius** [comment]
What is "collapsing an item"? I tried it i checked and unchecked, long pressed after checking and swiped after checking. Tried to drag and drop it down. No chance, it does not move.
With one press on the item i can remove or edit it. Using 2.0.5 from f-droid if thats changing something.

**Comment by Albert221** [comment]
Sorry, I wrote this comment as a todo for me, it's not possible now! :)

**Comment by logos88** [comment]
I see this option useful so it makes you to have a more easy control of what are the things you have left when you are in the super.

I would also, besides of putting the checked items at the bottom, make them to appear crossed out (like a typical paper list) or shaded, so you can identify very easily what is already in your basket and what is left.

**Comment by Albert221** [comment]
- [ ] Cross out done items
- [ ] Move items marked as done just below all not done items
