### ISSUE TITLE
Add a list in the backend

### ISSUE THREAD

**Issue by natrius** [Albert221/FastShopping#21]
Kind of, add all the stuff you might ever need in that list (probably with tags even? So it could be used for travelling as well. Tags: food;camping;travelling;... for example) and when creating a new list you can just add or remove stuff to the current list. 

Tagging would be the thing mentioned in https://github.com/Albert221/FastShopping/issues/19

**Comment by Albert221** [comment]
Can you please explain this feature more? I'm not sure what do you mean

**Comment by natrius** [comment]
If i create a list, i have to write in manually every item. If i delete the list for whatever reason, i have to write it in again. Everything. It would be better if every entry would be saved as list and when writing i get the things in the list as suggestion, for example. 
And if you make the list editable, why not, so i can sit down and include everything i want to buy in groceries and for travelling and when creating a list for a new trip (holiday or groceries) i don't have to write in everything individually. 

For the simple thing - just save it in the background. For the enhanced - make it editable.

**Comment by Albert221** [comment]
Thank you for your interest in the app and your suggestion!

This suggestion is very similar (if not the same) to #26. 

In https://github.com/Albert221/FastShopping/issues/26#issuecomment-744051419 I explained why I won't implement this feature.
