### ISSUE TITLE
No landscape mode

### ISSUE THREAD

**Issue by marmistrz** [Albert221/FastShopping#25]
The application forces portrait orientation. This is an issue while using a slider hardware keyboard.

**Comment by Albert221** [comment]
Do you think allowing the landscape orientation would be good, even though the app will, as a result, have much more whitespace?

![image](https://user-images.githubusercontent.com/4085280/90310209-d62c5100-deef-11ea-9207-9cac2f8acaab.png)

**Comment by marmistrz** [comment]
Yes, because it's still better than tilting your 90 degrees :) Possibly as opt-out, so that those who don't like it can disable rotation.

**Comment by Albert221** [comment]
It's already there! :)
