### ISSUE TITLE
Suggestion of frequently used items when adding

### ISSUE THREAD

**Issue by logos88** [Albert221/FastShopping#26]
Hi! First thanks for this app, I think is very clean and nice to use. One thing I miss though is an autocomplete suggestion when I add an item. This way, when I started to type an item, a list of other items used before and starting with the same letters would appear as options to select them and make the list faster (like in [OI Shopping List](https://github.com/openintents/shoppinglist)).

This would be an example from Listonic:

![image](https://user-images.githubusercontent.com/4170088/90273919-ff9d9c00-de5f-11ea-8730-657413f56dca.png)

You may look at "ShoLi" too, it is there in f-droid. Every item ever added to any list goes to default database which is never deleted unless user choose so explicitely. So whenever user wants to add an item to a list he can choose from default database or types few characters to search and autocomplete.

The only thing could change from each time when you add an item could be the number of pieces for each item. This maybe could be easily handed with a similar approach as [ShoppingList](https://github.com/woefe/ShoppingList), which gives an option when you add an item to add separatedly the number too, and the same if you want to edit than item:

New item:

![photo_2020-08-14_18-09-24](https://user-images.githubusercontent.com/4170088/90272145-3a520500-de5d-11ea-8836-1a0c259ea6f9.jpg)

Edit an item:

![photo_2020-08-14_18-36-40](https://user-images.githubusercontent.com/4170088/90272148-3d4cf580-de5d-11ea-835c-7f0d5415fab6.jpg)

**Comment by Albert221** [comment]
Hi, thanks for your interest in the app and your suggestion!

I, unfortunately, decided to not implement this feature in Fast Shopping. I find keyboard suggestions do a similar thing to what you described, but I understand how it would be better than the keyboard ones. Although, I don't think this fits in the goal and my image of what I'd want this application to be
