### ISSUE TITLE
Issue encountered with build_runner 'Bad state: Unexpected diagnostics'

### ISSUE THREAD

**Issue by bvenkysubbu** [Albert221/FastShopping#29]
Getting the following error -

```
My-MacBook-Pro:FastShopping User$ flutter packages pub run build_runner build
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 441ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 12.7s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.1s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] built_value_generator:built_value on test/app_test.dart:

Bad state: Unexpected diagnostics:
/Users/MyName/Downloads/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] built_value_generator:built_value on test/app_test.dart:

Bad state: Unexpected diagnostics:
/Users/MyName/Downloads/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] built_value_generator:built_value on test/app_test.dart:
```

**Comment by bvenkysubbu** [comment]
Looks like this is related to [https://github.com/flutter/flutter/issues/63556](this issue).

**Comment by bvenkysubbu** [comment]
Adding the following line to pubspec.yaml fixed the issue.

```
dependency_overrides:
  analyzer: '0.39.14'
```

Shall I raise a pull request for the same?

**Comment by Albert221** [comment]
I can't reproduce this issue. Works fine on my `1.21.0-9.2.pre`. What's your `flutter --version`?

`dependency_overrides` isn't really a good idea. It may be due to your local Flutter installation version incompatibility. I highly suggest upgrading to the newest beta. You can check out [fvm](https://github.com/befovy/fvm), awesome Flutter version manager that helps you manage many Flutter versions on one computer.

**Comment by bvenkysubbu** [comment]
$ flutter --version
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (7 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
