### ISSUE TITLE
Provide alternative download source for APK

### ISSUE THREAD

**Issue by IzzySoft** [Albert221/FastShopping#3]
Any chance to have your app available outside Play Store (for those who cannot or wantnot use that place, e.g. for privacy reasons)? Options would be attaching the APK to `releases/` – or even to bring it to [F-Droid](https://f-droid.org/). Thanks for considering!

**Comment by Albert221** [comment]
Hey, thanks for your interest in my project!

Of course, I totally forgot attaching APKs to tags on GitHub, now, the latest version [is available](https://github.com/Albert221/FastShopping/releases/tag/v1.1.0). So will next ones.

I wasn't considering putting this app on F-Droid, but I'm not rejecting that idea.

**Comment by IzzySoft** [comment]
Thanks Albert! I took the freedom then to add it to my repo (should [show up here](https://apt.izzysoft.de/fdroid/index/apk/me.wolszon.fastshopping) with tomorrow's sync). If you agree, I could trigger the process of adding it to the official F-Droid repo (disclosure: I'm one of the maintainers there) – same goes for LekBierz btw.

One last question: What license are your projects using? I couldn't find a hint on that.

**Comment by Albert221** [comment]
Currently, I'm working on the next major version for Fast Shopping, until the release, I will decide on the license. It will most likely be MIT or Apache 2.0.

**Comment by IzzySoft** [comment]
Thanks! Could you let me know when you've decided? For a listing in the official F-Droid repo, we'd need this.

**Comment by IzzySoft** [comment]
No pressure, just a heads-up: any news? And while on it, would you consider establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) (which would help with F-Droid as you could maintain description etc. yourself and even provide screenshots)?

**Comment by Albert221** [comment]
Hi! Currently, v2.0.1 is the most recent version; you can find the latest APK in the Releases section. Both screenshots and description can be found in Google Play and here: https://itsallwidgets.com/fast-shopping. I don't have any macOS device so Fastlane configuration isn't really helpful for me

**Comment by IzzySoft** [comment]
@Albert221 you misunderstood me. I know where to find the APK – I was rather referring to the F-Droid inclusion. [F-Droid](https://f-droid.org/) builds from source and does not accept binaries. And Fastlane got nothing to do with a Mac – it's rather a structure for apps' metadata, such as descriptions and screenshots, which F-Droid would automatically pick to show in its clients.

**Comment by Albert221** [comment]
Ah, right, sorry. I'll create a feature branch for that. I'd be more than happy if you could review it later.

**Comment by IzzySoft** [comment]
That looks fine, thanks! Once merged and the next tag being available, I could start the RFP (Request For Packaging) at F-Droid – pending your permission to do so (F-Droid wants the author to explicitly state he's at least not opposed to that).

**Comment by Albert221** [comment]
@IzzySoft you have my permission to publish FastShopping to F-Droid!

**Comment by IzzySoft** [comment]
Thanks @Albert221! I've [opened the RFP](https://gitlab.com/fdroid/rfp/-/issues/1258).

**Comment by Albert221** [comment]
I've looked into this RFP and Googled something. I'm not sure about that, but Flutter apps need a little different build process than normal Android ones.

According to [this](https://forum.f-droid.org/t/flutter-apps/4796). You may refer to [the linked Build script](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.nikhiljha.lobstersapp.yml), and after running the `flutter pub get` you may also want to run `flutter packages pub run build_runner build`, just like in the [README Building section](https://github.com/Albert221/FastShopping#building).

**Comment by IzzySoft** [comment]
Yes, our packagers will take care for that. The "build block" is set up when they pick up and test. I just provide the "metadata skeleton"; if I were a packager, I could have opened a merge request with the `.yml` file directly after testing the build. As it is, I am not a packager (or even an Android dev), so I leave that to my knowlegable collegues :wink: That way even a novice can open a RFP (actually, the variant/template I chose is already the "advanced version" using YAML formatting; the default one is even easier, to lower the barrier).

Thanks for caring, though!

**Comment by Albert221** [comment]
> Yes, our packagers will take care for that.

Oh, that's awesome the F-Droid works like that! I may want to dive into it someday :)

**Comment by IzzySoft** [comment]
You are welcome anytime! If you look for an intro/reading, may I recommend you my 3-part blog series on F-Droid? Starting point: [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1) :smiley: You might be especially interested in the second part: [F-Droid for advanced users and developers](https://android.izzysoft.de/articles/named/fdroid-intro-2).

**Comment by IzzySoft** [comment]
As expected, the F-Droid bot confirmed. RFP is now marked "ready" for packaging, so next a packager should pick it up (usually within a week – if not then, I'll ping them directly).

**Comment by Albert221** [comment]
How is the progress? :)

**Comment by IzzySoft** [comment]
Urn… Seems like our packagers missed it. Thanks for the heads-up, I've just pinged them directly and asked to pick up.
