### ISSUE TITLE
Uncheck all items in a list

### ISSUE THREAD

**Issue by andresterba** [Albert221/FastShopping#32]
First of all thank your for this app :tada: 

I would be pretty cool to have a button to uncheck all items in a list.
I'm not sure where to place the button, but maybe it could be integrated in the 'archive' button somehow?
Instead of archiving the list it would ask if you want to archive the list or simply uncheck all items in the specific list.

**Comment by logos88** [comment]
This could be useful to reuse a list, like a list with typical things to buy (bread, milk, ...)
