### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ashledombos** [Albert221/FastShopping#35]
Hello there,

I'm interested to join the French translation team (or to translate in French if nobody does already)

Thank you for this open source app!

Cheers

Raphaël

**Comment by Albert221** [comment]
Hi! Thank you for your interest in Fast Shopping!

I'll reach out to you once I'll have some free time to set up everything for you so you can start translating Fast Shopping :)

**Comment by Albert221** [comment]
I need to create an account for you on my instance of Arbify http://arb.wolszon.me/. Please, give me your email. You can send me it at albert+fastshopping@wolszon.me

**Comment by Albert221** [comment]
I created an account for you. Other than strings on Arbify, I need two strings for Google Play/F-Droid listing:

Hey, awesome, thank you! Please, check out Arbify once again. I just added contents for the screenshots that are visible in app stores.

- Short description (**max 80 characters**)
  English: Simple app for easy shopping list making, developed with simplicity in mind.
- Full description (max 4000 characters)
  English: Fast Shopping is a mobile application developed with simplicity in mind. It allows you to have a simple set of shopping lists, that you can easily manage. It contains no ads. Targetted to everyone who wants a simple app to get the job done. Not limited to tech-savvy users.

Let me know when those will be ready! :)

**Comment by ashledombos** [comment]
Hi Albert,

it's done :)

- Une application facilitant la création de listes de courses, développée dans un souci de simplicité.

- Fast Shopping est une application mobile développée dans un souci de simplicité, permettant de disposer d'un ensemble de listes de courses facile à gérer. Sans pubs, elle s'adresse à tous ceux qui veulent une application sans fioriture qui fasse bien son travail. Elle n'est pas limitée aux utilisateurs avertis.

cheers

**Comment by Albert221** [comment]
Awesome! There is one issue though, your short description's length is 101 characters, I **need** it to be 80 characters at most.

**Comment by ashledombos** [comment]
Oops sorry, I forgot to count characters. Your sentence is perfect :)

**Comment by ashledombos** [comment]
Great for the update :) BTW, will I be notified is there are new or modified strings?

**Comment by Albert221** [comment]
Yes! I have your email now in Arbify, I'll be emailing when there will be
new strings to translate :)

**Comment by ashledombos** [comment]
I noticed yesterday you're the author of Arbify, very nice work! I'd like to add it in Yunohost, it's a very handy tool for short strings translation project. It seems much lighter and easy to maintain than weblate.
