### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by rikishi0071** [Albert221/FastShopping#36]
Hi. I'd like to trsnslate this app to Russian. Would you like to open Transifex or something like that in order to let people translating this app to many languages and then you would commit translations?

**Comment by Albert221** [comment]
Hi! Thank you for your interest in Fast Shopping! I'm looking forward to having the app translated to Russian, but I'm currently low on time for this. I'll comment on this issue once I'll be able to set everything up for you :)

**Comment by Albert221** [comment]
I've created an account for you on my instance of Arbify. You should receive a confirmation email from it.

After confirming your account, you can proceed to translating strings to Russian! There are also few more stuff to be translated, but this is the essential. Ping me here when you'll be done or when you'll have any question.

https://arb.wolszon.me/projects/3/messages

**Comment by rikishi0071** [comment]
I've finished translating strings in Arbify. Wrote an email to you.

**Comment by Albert221** [comment]
Hey, awesome, thank you! Please, check out Arbify once again. I just added contents for the screenshots that are visible in app stores.

Also, I need this:

- App title (max 50 characters)
- Short description (max 80 characters)
- Full description (max 4000 characters)

**Comment by rikishi0071** [comment]
Hello. I've finished translation in Arbify.

1. App title
Список покупок
2. Short description
Простое приложение для лёгкого составления списка покупок, разработанное с оглядкой на простоту.
3. Full description
Список покупок - это мобильное приложение, разработанное с оглядкой на простоту. Оно позволяет вам составить простую коллекцию продуктовых списков, которыми вы можете легко управлять. Приложение не содержит рекламы. Предназначено для всех, кто хочет иметь простое приложение для составления списков покупок. Для использования приложения не требуются технические навыки.

**Comment by Albert221** [comment]
Thank you once again. I'll update and merge the #37 shortly.

I'll change the name of the app to _Быстрые Покупки_ though.
