### ISSUE TITLE
Make Back Button Go To List of Lists Instead Of Quit

### ISSUE THREAD

**Issue by landry314** [Albert221/FastShopping#41]
When viewing a list it is not intuituve to exit the app when the back button is pressed. It is intuitive to back out to the main screen with the list of all lists.

I have many lists and when I need to change lists I need to tap the bottom to open a drawer which is not clear. I have to learn this is the way and it isnt obvious.

Another way to look at it is why would the user want to exit the app at this point? If I want to exit the app, I hit the home button or the app switcher button. The way this function works now doesnt add anything to the app, it only detracts!

Thanks for a simple list app! Just what I needed!

**Comment by Albert221** [comment]
I'm not sure whether this would be something that the users would expect from their Back button. I'll leave this issue open so that the others can provide their feedback

**Comment by logos88** [comment]
Personally, I'd back out to the main screen in the case other "current" list exist. Otherwise, I would close the app.
