### ISSUE TITLE
Icons for shopping items

### ISSUE THREAD

**Issue by dominikheinz** [Albert221/FastShopping#45]
Adding a small icon next to the entry would be a nice addition to not only make the app look more appealing, but one would also be able to find certain entries faster (Seeing the icon vs reading the icon text).

However, instead of having 10000 different icons for every possible entry, it would probably make more sense to have a set of icons for certain categories of items (vegetables, fruits, drinks, electronics, clothes etc).
Once an entry is recognized as an items from a predefined list (Related: #44) it would show the corresponding category icon next to it, otherwise a generic placeholder icon is shown.

There are plenty of icon sets that are free to use, - here is an example: https://icons8.com/icon/pack/food/dusk
There are probably more, this was just the first one I found.

**Comment by Albert221** [comment]
Thanks for the idea!

Unfortunately, I won't be developing it. Adding icons to entries requires either adding an icon picker that the user should use or somehow recognizing the category of an item from its name, the first one makes adding or editing items a little bit more complex and the second one is just not doable for me, not with the support for all the languages the app supports now and will in the future.

Also, it would be quite hard to compose the icon into the item tiles while still having the checkbox present.
