### ISSUE TITLE
No v3.0.0 tag

### ISSUE THREAD

**Issue by relan** [Albert221/FastShopping#46]
pubspec.yaml says the latest version is 3.0.0+17, but there's no v3.0.0 tag in the repository. This prevents F-Droid from building this version: https://f-droid.org/wiki/page/me.wolszon.fastshopping/lastbuild_17

**Comment by Albert221** [comment]
Fast Shopping 3.0.0 is not yet ready. There are still a few things I want to be done before releasing the 3.0.0 version. Look at the [v3.0.0 milestone](https://github.com/Albert221/FastShopping/milestone/4).

**Comment by licaon-kter** [comment]
Disabled 3.0.0 for now, we waste time on it. Ping us when it's actually tagged

https://f-droid.org/wiki/index.php?title=me.wolszon.fastshopping/lastbuild_17&action=history

**Comment by Albert221** [comment]
Will do!
